pipeline:
  name: New
  identifier: New
  projectIdentifier: Demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1689838783895
        repoName: https://github.com/deepz-here/Testrepo9977.git
        build: <+input>
  delegateSelectors:
    - docker-delegate
